### ISSUE TITLE
Module not registered in graph

### ISSUE THREAD

**Issue by luccastanan** [PeelTechnologies/react-native-tcp#88]
`error: bundling failed: ReferenceError: Module not registered in graph: /Users/luccasgaluppotanan/Documents/Desenvolvimento/React Native/SocketTest/index.js
    at graph.entryPoints.forEach.entryPoint (/Users/luccasgaluppotanan/Documents/Desenvolvimento/React Native/SocketTest/node_modules/metro/src/DeltaBundler/traverseDependencies.js:331:13)
    at Array.forEach (<anonymous>)
    at reorderGraph (/Users/luccasgaluppotanan/Documents/Desenvolvimento/React Native/SocketTest/node_modules/metro/src/DeltaBundler/traverseDependencies.js:327:21)
    at /Users/luccasgaluppotanan/Documents/Desenvolvimento/React Native/SocketTest/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:203:19
    at Generator.next (<anonymous>)
    at step (/Users/luccasgaluppotanan/Documents/Desenvolvimento/React Native/SocketTest/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:11:198)
    at /Users/luccasgaluppotanan/Documents/Desenvolvimento/React Native/SocketTest/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:11:358
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by ihimanshurawat** [comment]
any solutions?

**Comment by ChuotNhat** [comment]
you try npm install --update-binary

**Comment by lac123** [comment]
r u a sb ?

**Comment by lac123** [comment]
2b

**Comment by yolo001** [comment]
I have the same isuue, first delete node_modules in your root project and then `npm install` then run again
